---
- name: setup PHP Composer
  shell: creates=/usr/local/bin/composer
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

- name: install msgpack extension
  command: pecl install msgpack

- name: activate xdebug
  lineinfile:
    line: 'xdebug.mode=debug'
    path: /etc/php/8.4/cli/conf.d/20-xdebug.ini

- name: start it for all CLI invocation
  lineinfile:
    line: 'xdebug.start_with_request=yes'
    path: /etc/php/8.4/cli/conf.d/20-xdebug.ini

