---
- name: add yarn repo's key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: put yarn repository
  apt_repository:
    repo: deb http://dl.yarnpkg.com/debian/ stable main
    state: present

- name: add nodesource repo's key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    state: present

- name: put nodesource repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_20.x nodistro main'
    state: present

- name: install nodejs and npm from repo
  apt: name="{{ item }}"
    state=present
    update_cache='yes'
  with_items:
    - nodejs
    - yarn
