---
  - name: Add neovim ppa 
    apt_repository: repo="ppa:neovim-ppa/stable" state=present
 
  - name: Install neovim from ppa
    apt: name="neovim" state="present"

# install node (for coc.vim)
  - name: add yarn repo's key
    apt_key:
      url: https://dl.yarnpkg.com/debian/pubkey.gpg
      state: present 

  - name: put yarn repository
    apt_repository:
      repo: deb http://dl.yarnpkg.com/debian/ stable main
      state: present

  - name: add nodesource repo's key
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: put nodesource repository
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"
      state: present

  - name: install nodejs and npm from repo
    apt: 
      name="{{ item }}"
      state=present
      update_cache='yes'
    with_items:
      - nodejs
      - yarn

# install vim-plug

  - name: Make "{{ neovim_config_dir }}/autoload" directory
    file: path="{{ neovim_config_dir }}/autoload" state=directory
    become: yes
    become_user: vagrant

  - name: Make "{{ neovim_data_dir }}/plugged" directory
    file: path="{{ neovim_data_dir }}/plugged" state=directory
    become: yes
    become_user: vagrant

  - name: Install vim-plug
    get_url:
      url: " https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
      dest: "{{ neovim_config_dir }}/autoload/plug.vim"
    become: yes
    become_user: vagrant

# install deoplete

  - name: Installing neovim pip3 package
    pip:
      name: neovim
      executable: pip3

  - name: Installing pynvim pip3 package
    pip:
      name: pynvim
      executable: pip3

# Copy the init file
  - name: copy init files in rc folder
    copy:
      src="init.vim"
      dest="{{ neovim_config_dir }}/init.vim"
      owner="{{ username }}"
      group="{{ username }}"
      mode=0640

# install vim plugins
  - name: Install vim plugins
    command: nvim --headless '+silent!' '+PlugInstall!' '+qall!'
    become: yes
    become_user: vagrant

  - name: Install ripgrep for fzf plugin
    get_url:
      url="https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb"
      dest="/tmp/ripgrep.deb"

  - name: Install bat to have color in ripgrep
    get_url:
      url="https://github.com/sharkdp/bat/releases/download/v0.15.4/bat_0.15.4_amd64.deb"
      dest="/tmp/bat.deb"

  - name: Install ripgrep
    apt: deb="/tmp/ripgrep.deb"
    become: yes

  - name: Install bat
    apt: deb="/tmp/bat.deb"
    become: yes

# install vscode extension to provide debugger to neovim
  - name: Download vscode-php-debug
    get_url:
      url=https://codeload.github.com/xdebug/vscode-php-debug/zip/refs/heads/main
      dest="/tmp/vscode-php-debug.zip"

  - unarchive:
      src: /tmp/vscode-php-debug.zip
      dest: /home/vagrant
