---
  - name: Add neovim ppa 
    apt_repository: repo="ppa:neovim-ppa/unstable" state=present
 
  - name: Install neovim from ppa
    apt: name="neovim" state="present"

  - name: Set up alternatives for Neovim
    ansible.builtin.alternatives:
      name: "{{ item.name }}"
      path: /bin/nvim
      link: "/usr/bin/{{ item.name }}"
      priority: 100
    become: true
    loop:
      - name: vi
      - name: vim
  
# install vim-plug

  - name: Make "{{ neovim_config_dir }}/autoload" directory
    file: path="{{ neovim_config_dir }}/autoload" state=directory
    become: yes
    become_user: vagrant

  - name: Make "{{ neovim_data_dir }}/plugged" directory
    file: path="{{ neovim_data_dir }}/plugged" state=directory
    become: yes
    become_user: vagrant

  - name: Install vim-plug
    get_url:
      url: " https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
      dest: "{{ neovim_config_dir }}/autoload/plug.vim"
    become: yes
    become_user: vagrant

# Copy the init file
  - name: copy init files in rc folder
    copy:
      src="init.vim"
      dest="{{ neovim_config_dir }}/init.vim"
      owner="{{ username }}"
      group="{{ username }}"
      mode=0640

# install vim plugins
  - name: Install vim plugins
    command: nvim --headless '+silent!' '+PlugInstall!' '+qall!'
    become: yes
    become_user: vagrant

  - name: Install ripgrep for fzf plugin
    apt: name="ripgrep" state="present"

  - name: Install bat to have color in ripgrep
    apt: name="bat" state="present"

  - name: Install fswatch to workaround neovim issues 23291
    apt: name="fswatch" state="present"

# install vscode extension to provide debugger to neovim
  - name: Download vscode-php-debug
    get_url:
      url=https://codeload.github.com/xdebug/vscode-php-debug/zip/refs/heads/main
      dest="/tmp/vscode-php-debug.zip"
    become: yes

  - unarchive:
      src: /tmp/vscode-php-debug.zip
      dest: /opt
    become: yes

  - name: npm install
    command:
    args:
      cmd: npm install
      chdir: /opt/vscode-php-debug-main
    become: yes

  - name: npm run build
    command:
    args:
      cmd: npm run build
      chdir: /opt/vscode-php-debug-main
    become: yes

  - name: gives permission to read to everybody
    command:
    args:
      cmd: chmod a+w -R .
      chdir: /opt/vscode-php-debug-main
    become: yes
