---
  - name: Add neovim ppa 
    apt_repository: repo="ppa:neovim-ppa/stable" state=present
 
  - name: Install neovim from ppa
    apt: name="neovim" state="present"

# install vim-plug

  - name: Make "{{ neovim_config_dir }}/autoload" directory
    file: path="{{ neovim_config_dir }}/autoload" state=directory
    become: yes
    become_user: vagrant

  - name: Make "{{ neovim_data_dir }}/plugged" directory
    file: path="{{ neovim_data_dir }}/plugged" state=directory
    become: yes
    become_user: vagrant

  - name: Install vim-plug
    get_url:
      url: " https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
      dest: "{{ neovim_config_dir }}/autoload/plug.vim"
    become: yes
    become_user: vagrant

# install deoplete

  - name: Installing neovim pip3 package
    pip:
      name: neovim
      executable: pip3

  - name: Installing pynvim pip3 package
    pip:
      name: pynvim
      executable: pip3

# Copy the init file
  - name: copy init files in rc folder
    copy:
      src="init.vim"
      dest="{{ neovim_config_dir }}/init.vim"
      owner="{{ username }}"
      group="{{ username }}"
      mode=0640

# install vim plugins
  - name: Install vim plugins
    command: nvim '+silent!' '+PlugInstall!' '+qall!'
    become: yes
    become_user: vagrant

  - name: Install ripgrep for fzf plugin
    get_url:
      url="https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb"
      dest="/tmp/ripgrep.deb"

  - name: Install bat to have color in ripgrep
    get_url:
      url="https://github.com/sharkdp/bat/releases/download/v0.15.4/bat_0.15.4_amd64.deb"
      dest="/tmp/bat.deb"

  - name: Install ripgrep
    apt: deb="/tmp/ripgrep.deb"
    sudo: true

  - name: Install bat
    apt: deb="/tmp/bat.deb"
    sudo: true
