---
- name: copy config files in rc folder
  copy: src=.vimrc dest={{ home }}/.vimrc
  sudo: vagrant

- name: Create ~/.vim folder
  file: dest={{ home }}/.vim state=directory
  sudo: vagrant

- name: Create ~/src folder
  file: dest={{ home }}/src/vim-pathogen state=directory
  sudo: vagrant

# pathogen
- name: Check out pathogen
  git:
      repo=https://github.com/tpope/vim-pathogen.git
      dest={{ home }}/src/vim-pathogen
  sudo: vagrant

- name: Create ~/.vim/autoload folder
  file: dest={{ home }}/.vim/autoload state=directory
  sudo: vagrant

- name: Symlink pathogen into ~/.vim/autoload
  file:
      src={{ home }}/src/vim-pathogen/autoload/pathogen.vim
      dest={{ home }}/.vim/autoload/pathogen.vim
      state=link
  sudo: vagrant

#
- name: Check out syntastic
  git:
    repo=https://github.com/scrooloose/syntastic.git
    dest={{ home }}/.vim/bundle/syntastic
  sudo: vagrant
#
- name: Checkout Padawan.vim
  git:
    repo=https://github.com/mkusher/padawan.vim.git
    dest={{ home }}/.vim/bundle/padawan.vim.git
  sudo: vagrant

#
- name: Checkout Padawan symfony plugin
  git:
    repo=https://github.com/mkusher/padawan.php-symfony.git
    dest={{ home }}/.vim/bundle/padawan.php-symfony.git
  sudo: vagrant

#
- name: Install Padawan
  command: composer global require mkusher/padawan
  sudo: vagrant

#
- name: Checkout abolish
  git:
    repo=https://github.com/tpope/vim-abolish.git
    dest={{ home }}/.vim/bundle/vim-abolish
    update=yes
  sudo: vagrant

#

- name: Install apt packages for YouCompleteMe vim completion engine
  sudo: yes
  apt:
    name={{ item }} state=latest
  with_items:
    - build-essential
    - cmake
    - python-dev
- name: Check out YouCompleteMe
  git:
    repo=https://github.com/Valloric/YouCompleteMe.git
    dest={{ home }}/src/YouCompleteMe
    force=yes
  sudo: vagrant
- name: Symlink YouCompleteMe to ~/vim/bundle
  file:
    src={{ home }}/src/YouCompleteMe
    dest={{ home }}/.vim/bundle/YouCompleteMe
    state=link
  sudo: vagrant
- name: Compile YouCompleteMe binaries
  command: ./install.sh --clang-completer
    chdir={{ home }}/src/YouCompleteMe
    creates={{ home }}/src/YouCompleteMe/third_party/ycmd/ycm_core.so
  sudo: vagrant
