---
- hosts: all
  sudo: true
  vars:
      home: /home/vagrant
      APPDIR: /vagrant
  environment:
    APP_DB_NAME: "{{ DBNAME }}"
    APP_DB_USER_NAME: "{{ DBUSER }}"
    APP_DB_PASSWORD: "{{ DBPASSWORD }}"
  pre_tasks:
    - name: check last APT update time
      apt: update_cache=yes cache_valid_time=86400
    - name: Install stuff from Aptitude
      apt: name={{ item }} state=installed
      with_items:
       - git
       - tig
       - vim
       - bash-completion # Not included in the docker image
       - postgresql-client
       - libzip2
       - tree
       - htop
       - man-db

  roles:
    - {role: zsh, sudo: false}
    - {role: symfony, sudo: false}
    - {role: vim, sudo: false}
