---
- name: setup framework installer
  shell: creates=/usr/local/bin/symfony
    curl -LsS http://symfony.com/installer -o /usr/local/bin/symfony

- name: make framework installer executable
  file: path=/usr/local/bin/symfony mode='a+x'

